markdown: GFM
title: home / saurish-chakrabarty /
description: Home Page of Saurish Chakrabarty, Department of Physics, Acharya Prafulla Chandra College
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
github:
  is_project_page: false
