markdown: GFM
title: Saurish Chakrabarty
description: Home Page of Saurish Chakrabarty, Department of Physics, Acharya Prafulla Chandra College
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
